apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: audio-0712
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  audio-0712
    app.kubernetes.io/part-of: audio-0712  
  name: audio-0712
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  audio-0712 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  audio-0712
    spec:
      containers:
      - env:
        - name: MODEL_ENDPOINT
          value: http://audio-0712-model-server:8001
        image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true