apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: audio-0712
  janus-idp.io/tekton: audio-0712
  backstage.io/kubernetes-id: audio-0712
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: audio-0712
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml